### ISSUE TITLE
Style issues on chrome

### ISSUE THREAD

**Issue by Koed00** [mmistakes/hpstr-jekyll-theme#109] opened 2015-08-04 08:37 UTC
I've seen this happen on chrome a few times. It doesn't always happen and usually a reload clears it. 
![image](https://cloud.githubusercontent.com/assets/3934261/9056631/b9858314-3a94-11e5-8557-a57cd1e8080d.png)

Any idea how to fix this? It only seems to happen with anchors.

**Comment by mmistakes** [comment] 2015-08-04 19:25
If you can come up with a set of conditions so I can reproduce it I'll take a look. Otherwise if I had to guess maybe it's something going on with how Chrome is interpreting the space an anchor takes up and that changes once the webfont loads since it's likely wider than the system font.

**Comment by Koed00** [comment] 2015-08-04 19:34
Fair enough, but I'll doubt I will be able to reproduce it consistently. I was hoping it was a known issue.

**Comment by maxpou** [comment] 2016-05-26 08:41
Cannot reproduce too.
Please, provide markdown content.

**Comment by mmistakes** [comment] 2016-06-27 20:05
Closing as I can't reproduce it. If you can provide a repo and the exact steps to reproduce the problem , then please reopen the issue.

**Closed by mmistakes** 2016-06-27 20:05 UTC
Labels: Status: Pending
